from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import os


def create_pdf(
    filename,
    company,
    ats_score,
    match_percent,
    skills,
    missing_skills,
    suggestions
):

    # Create reports folder
    if not os.path.exists("reports"):
        os.makedirs("reports")

    pdf_name = os.path.splitext(filename)[0] + "_ATS_Report.pdf"
    pdf_path = os.path.join("reports", pdf_name)

    c = canvas.Canvas(pdf_path, pagesize=A4)

    width, height = A4

    y = height - 50

    # ---------------- Title ----------------

    c.setFont("Helvetica-Bold", 20)
    c.drawString(170, y, "ResumeIQ ATS Report")

    y -= 40

    c.setFont("Helvetica", 12)

    c.drawString(50, y, f"Company : {company}")

    y -= 25

    c.drawString(50, y, f"ATS Score : {ats_score}%")

    y -= 25

    c.drawString(50, y, f"Job Match : {match_percent}%")

    y -= 40

    # ---------------- Skills ----------------

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Detected Skills")

    y -= 25

    c.setFont("Helvetica", 12)

    if skills:
        for skill in skills:

            c.drawString(70, y, "• " + skill)

            y -= 20

            if y < 80:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 12)
    else:
        c.drawString(70, y, "No skills detected")
        y -= 20

    # ---------------- Missing Skills ----------------

    y -= 20

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Missing Skills")

    y -= 25

    c.setFont("Helvetica", 12)

    if missing_skills:
        for skill in missing_skills:

            c.drawString(70, y, "• " + skill)

            y -= 20

            if y < 80:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 12)
    else:
        c.drawString(70, y, "No missing skills")
        y -= 20

    # ---------------- Suggestions ----------------

    y -= 20

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "AI Suggestions")

    y -= 25

    c.setFont("Helvetica", 12)

    if suggestions:
        for suggestion in suggestions:

            c.drawString(70, y, "• " + suggestion)

            y -= 20

            if y < 80:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 12)
    else:
        c.drawString(70, y, "No suggestions")

    y -= 40

    c.setFont("Helvetica-Bold", 12)

    c.drawString(
        50,
        y,
        "Generated by ResumeIQ AI Resume Analyzer"
    )

    c.save()

    return pdf_path